/**:
  ros__parameters:
    input_topic: /goal_pose
    ego_goal_topic: /move_base_simple/goal
    normalized_goal_topic: /ground/planning/goal
    goal_marker_topic: /ground/planning/goal_marker
    frame_id: odom
    tf_timeout_sec: 0.2
